/**
 * Reporting Domain — types exported to the frontend layer.
 *
 * @traceability CANONICAL-DOMAIN-MODEL.md: Aggregate 10 (ReportingAggregate)
 * @traceability DOC-006: Reporting concept
 * @traceability DOC-021: Physical Data Model report tables
 * @traceability ASS-001: Application Services for report generation
 */

/* ------------------------------------------------------------------ */
/*  Value Objects                                                      */
/* ------------------------------------------------------------------ */

/**
 * Report type.
 */
export type ReportType = 'balance_sheet' | 'income_statement' | 'cash_flow' | 'ledger' | 'custom';

/**
 * Report period type.
 */
export type ReportPeriod = 'daily' | 'weekly' | 'monthly' | 'quarterly' | 'yearly';

/* ------------------------------------------------------------------ */
/*  Entities                                                           */
/* ------------------------------------------------------------------ */

/**
 * ReportDefinition — template for generating reports.
 * Maps to physical table `report_templates` in POSTGRESQL-SCHEMA-PACK-v1.md.
 */
export interface ReportDefinition {
  /** Universally unique identifier for this report definition. */
  readonly id: string;

  /** Organization this report belongs to. */
  readonly organizationId: string;

  /** Report code/key (e.g., 'balance-sheet', 'income-statement'). */
  readonly code: string;

  /** Report title. */
  readonly title: string;

  /** Report description. */
  readonly description: string;

  /** Report type. */
  readonly type: ReportType;

  /** Default period (monthly by default). */
  readonly defaultPeriod: ReportPeriod;

  /** Whether this is a system report. */
  readonly isSystem: boolean;

  /** Version for optimistic locking. */
  readonly version: number;

  /** Whether this record is synced with the server. */
  readonly synced: boolean;

  /** Timestamp when this record was created (UTC ISO 8601). */
  readonly createdAt: string;

  /** Timestamp of last modification (UTC ISO 8601). */
  readonly updatedAt: string;
}

/**
 * ReportGenerated — an generated report instance.
 */
export interface ReportGenerated {
  /** Universally unique identifier for this report instance. */
  readonly id: string;

  /** Reference to the report definition. */
  readonly reportDefinitionId: string;

  /** Organization this report belongs to. */
  readonly organizationId: string;

  /** Report generation period start date. */
  readonly periodStart: string;

  /** Report generation period end date. */
  readonly periodEnd: string;

  /** Report period type. */
  readonly period: ReportPeriod;

  /** Report type. */
  readonly type: ReportType;

  /** Generated data (JSON). */
  readonly data: Record<string, unknown>;

  /** Report status (draft, generated, failed, archived). */
  readonly status: 'draft' | 'generated' | 'failed' | 'archived';

  /** Generated by user ID. */
  readonly generatedBy: string;

  /** Generation timestamp. */
  readonly generatedAt: string;

  /** Expiration timestamp (if applicable). */
  readonly expiresAt: string | null;

  /** Version for optimistic locking. */
  readonly version: number;

  /** Whether this record is synced with the server. */
  readonly synced: boolean;

  /** Timestamp when this record was created (UTC ISO 8601). */
  readonly createdAt: string;

  /** Timestamp of last modification (UTC ISO 8601). */
  readonly updatedAt: string;
}

/**
 * ReportSnapshot — a snapshot of financial data at a point in time.
 */
export interface ReportSnapshot {
  /** Universally unique identifier for this snapshot. */
  readonly id: string;

  /** Organization this snapshot belongs to. */
  readonly organizationId: string;

  /** Snapshot date (UTC). */
  readonly snapshotDate: string;

  /** Financial metrics. */
  readonly metrics: Record<string, number>;

  /** Currency snapshot. */
  readonly currency: string;

  /** Version for optimistic locking. */
  readonly version: number;

  /** Whether this record is synced with the server. */
  readonly synced: boolean;

  /** Timestamp when this record was created (UTC ISO 8601). */
  readonly createdAt: string;

  /** Timestamp of last modification (UTC ISO 8601). */
  readonly updatedAt: string;
}

/* ------------------------------------------------------------------ */
/*  Command / Request DTOs                                             */
/* ------------------------------------------------------------------ */

/**
 * Input for ListReports definition query.
 */
export interface ListReportsDefinitionInput {
  /** Organization ID. */
  readonly organizationId: string;

  /** Filter by type (optional). */
  readonly type?: ReportType;

  /** Pagination: page number (default: 1). */
  readonly page?: number;

  /** Pagination: items per page (default: 20, max: 100). */
  readonly limit?: number;
}

/**
 * Input for GenerateReport command.
 */
export interface GenerateReportInput {
  /** Report definition ID. */
  readonly reportDefinitionId: string;

  /** Organization ID. */
  readonly organizationId: string;

  /** Period start date (ISO 8601). */
  readonly periodStart: string;

  /** Period end date (ISO 8601). */
  readonly periodEnd: string;

  /** Period type. */
  readonly period: ReportPeriod;

  /** Whether to include attachments (PDF, Excel). */
  readonly includeAttachments?: boolean;
}

/**
 * Input for ListReportInstances query.
 */
export interface ListReportInstancesInput {
  /** Organization ID. */
  readonly organizationId: string;

  /** Filter by report type (optional). */
  readonly type?: ReportType;

  /** Filter by status (optional). */
  readonly status?: 'draft' | 'generated' | 'failed' | 'archived';

  /** Date range start (optional). */
  readonly dateFrom?: string;

  /** Date range end (optional). */
  readonly dateTo?: string;

  /** Pagination: page number (default: 1). */
  readonly page?: number;

  /** Pagination: items per page (default: 20, max: 100). */
  readonly limit?: number;
}

/* ------------------------------------------------------------------ */
/*  Query / Response Types                                             */
/* ------------------------------------------------------------------ */

/**
 * Generic pagination response.
 */
export interface PaginatedResponse<T> {
  readonly items: ReadonlyArray<T>;
  readonly totalCount: number;
  readonly hasNextPage: boolean;
}

/**
 Report with generated data preview.
 */
export interface ReportInstanceWithPreview {
  /** The report instance. */
  readonly report: ReportGenerated;

  /** Preview of generated data (first 500 chars). */
  readonly preview: string;
}

/**
 Aggregated structure returned by useReports().
 */
export interface ReportsDomainModel {
  /** Report definitions. */
  readonly definitions: ReadonlyArray<ReportDefinition>;

  /** Generated report instances. */
  readonly instances: ReadonlyArray<ReportInstanceWithPreview>;

  /** Total count matching filters. */
  readonly totalCount: number;

  /** Currently selected report (if any). */
  readonly selectedReport: ReportGenerated | null;

  /** Loading state. */
  readonly isLoading: boolean;

  /** Error state (if any). */
  readonly error: string | null;
}

/**
 Aggregated structure returned by useReportSnapshot().
 */
export interface ReportSnapshotDomainModel {
  /** The snapshot. */
  readonly snapshot: ReportSnapshot | null;

  /** Loading state. */
  readonly isLoading: boolean;

  /** Error state (if any). */
  readonly error: string | null;
}

/* ------------------------------------------------------------------ */
/*  WatermelonDB Attributes                                            */
/* ------------------------------------------------------------------ */

/**
 * Attributes for the ReportGenerated WatermelonDB model.
 */
export interface ReportGeneratedAttrs {
  id: string;
  _updatedAt: number;
  organizationId: string;
  reportDefinitionId: string;
  periodStart: string;
  periodEnd: string;
  period: ReportPeriod;
  type: ReportType;
  data: string; // JSON serialized
  status: 'draft' | 'generated' | 'failed' | 'archived';
  generatedBy: string;
  generatedAt: string;
  expiresAt: string | null;
  version: number;
  synced: boolean;
  createdAt: string;
  updatedAt: string;
}

/**
 * Attributes for the ReportSnapshot WatermelonDB model.
 */
export interface ReportSnapshotAttrs {
  id: string;
  _updatedAt: number;
  organizationId: string;
  snapshotDate: string;
  metrics: string; // JSON serialized
  currency: string;
  version: number;
  synced: boolean;
  createdAt: string;
  updatedAt: string;
}